Documents/Django-Projs/Djangoweb1/Accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views
app_name='Accounts'

urlpatterns = [
        url(r'^login/$',auth_views.login,{'template_name':'registration/login.html'},name = 'login'),
        url(r'^register/$',views.UserFormView.as_view(),name = 'register')
]

Documents/Django-Projs/Djangoweb1/Djangoweb1/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', include('Home.urls',namespace = 'Home')),
    url(r'^admin/', admin.site.urls),
    url(r'^Music/', include('Music.urls',namespace = 'Music')),
    url(r'^Accounts/', include('Accounts.urls',namespace = 'Accounts')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT )
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Documents/Django-Projs/Djangoweb1/Home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
        url(r'^$',views.index ,name= 'index'),

]

Documents/Django-Projs/Djangoweb1/Home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Documents/Django-Projs/Djangoweb1/Home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render

def index(request):
    return render(request,'Home/index.html')

Documents/Django-Projs/Djangoweb1/Home/templates/Home/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}BEAT{% endblock %}</title>
        <!-- Loads all the statics files -->
        {% load staticfiles %}
        <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.png' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type"text/css" href="{% static 'Home/style.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    </head>
        <body>

            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                <!-- logo header-->
                    <div class="navbar-header">
                        <button type="button" class ="navbar-toggle" data-toggle="collapse" data-target="#TopNavBar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'Home:index'%}">BEAT</a>
                    </div>

                    <!--Items -->
                    <div class="collapse navbar-collapse" id="TopNavBar">

                        <ul class="nav navbar-nav">

                            <li class="">
                                <a href="{% url 'Home:index' %}">
                                    <span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>&nbsp;
                                    My Beat
                                </a>
                            </li>

                            <li class="">
                                <a href="#">
                                    <span class="glyphicon glyphicon-equalizer" aria-hidden="true"></span>&nbsp;
                                    Explore
                                </a>
                            </li>

                        </ul>

                        <form class="navbar-form navbar-left" role="search" method="get" action="#">

                            <div class="form-group">
                                <input type="text" class="form-control" name="q" value=""/>
                            </div>

                            <button type="submit" class="btn btn-default" > Search</button>
                        </form>

                       <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="{% url 'Home:index' %}">
                                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                                    Help
                                </a>
                           </li>

                           <li class="">
                                <a href="{% url 'Accounts:register' %}">
                                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                                    Signup
                                </a>
                           </li>

                            <li class="">
                                <a href=" {%url 'Accounts:login'%}">
                                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp;
                                    Login
                                </a>
                            </li>

                        </ul>

                    </div>
                </div>
            </nav>

        {% block body%}
	    {% endblock %}
        </body>

</html>

Documents/Django-Projs/Djangoweb1/Home/templates/Home/index.html
{% extends 'Home/base.html' %}